name       : libspectrum
version    : 1.4.4
release    : 2
source     :
    - https://sourceforge.net/projects/fuse-emulator/files/libspectrum/1.4.4/libspectrum-1.4.4.tar.gz/download : fdfb2b2bad17bcfc98c098deaebf2a9811824b08d525172436d5eb134c9780b1
license    : GPL-2.0-or-later
component  : programming.library
summary    : libspectrum is a library designed to make the input and output of some ZX Spectrum emulator files slightly easier
description: |
    libspectrum is a library designed to make the input and output of some ZX Spectrum emulator files slightly easier
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
