name       : libspectrum
version    : 1.3.0
release    : 1
source     :
    - http://heanet.dl.sourceforge.net/project/fuse-emulator/libspectrum/1.3.0/libspectrum-1.3.0.tar.gz : b587774da3e089054216e91c49fbcaeb62d499348adfccaee3657888de893e42
license    : GPL-2.0
component  : programming
summary    : libspectrum is a library designed to make the input and output of some ZX Spectrum emulator files slightly easier
description: |
    libspectrum is a library designed to make the input and output of some ZX Spectrum emulator files slightly easier
builddeps  :
    - gcc
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
